### ISSUE TITLE
SSL connection option for Redis Client module

### ISSUE THREAD

**Issue by samlanza** [grafana/xk6-redis#24] opened 2023-08-28 14:22 UTC
### Feature Description

The K6 Redis Client is currently missing an option to connect with SSL.  It connects via TCP by default.

### Suggested Solution (optional)

We have our Azure Redis servers set to only accept SSL connections.  This is to prevent man-in-the-middle attacks.  It would be nice to have the ability to connect using SSL with the K6 Redis Client.

**Comment by mstoykov** [comment] 2023-08-28 14:25
Hi @samlanza, thanks for reporting this. 

I have moved the issue to the repo that hosts the code for the experimental redis module.

This was already reported and some work has been done to fix it in #17 to support it.

I will be closing as this is duplicate of #13 and #14. Please follow them for more info.

**Closed** 2023-08-28 14:45 UTC
Labels: triage
